@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}


@startuml
package "ru.alexanna.cloud.io.server" {
class ClientHandler implements Runnable
ServerIO *--> Runnable
ClientHandler *-- ClientMsgProcessor
FileCommand --* ClientMsgProcessor
class FileCommandExecutor implements FileCommand
}

interface Runnable
interface FileCommand {
+ {abstract} getFilesList()
+ {abstract} upload()
+ {abstract} download()
+ {abstract} changeCurrentDir()
+ {abstract} copy()
+ {abstract} delete()
+ {abstract} move()
}

class ClientMsgProcessor {
- FileCommand command

}

class ServerIO {
ServerMessageHandler msgHandler
}

class ClientHandler {
- Path clientDir
- DataInputStream is
- DataOutputStream os
- Socket incomingSocket
- ClientMsgProcessor msgProcessor
+ ServerHandlerIO(Socket incomingSocket)
+ void run()
- void processMessage(byte msg)
}
@enduml